### ISSUE TITLE
Feature Request: Ability to Rename the Markdown Files

### ISSUE THREAD

**Issue by dylan-k** [vip20/vscode-agile-board#10]
Fantastic extension. I could see using this a whole lot. I especially like it for the way it's also accessible as markdown files, but about that... the accessibility and utility could be improved. Outside of the extension, a filename like `_kei1dfird_1.md` simply doesn't do, because it's meaningless, I can't search for it by name, or even pick it from a files list. 

Instead, perhaps, could it auto-rename according to the name of the item on the board, or allow for the markdown file to be changed? I guess it'll have to update the index too, and if you make the edit outside the extension you'll have to do that as well, but it's worth it for the longevity and accessibility of the files involved.

Anyway, thanks for listening and keep up the great work.

**Comment by vip20** [comment]
@dylan-k thanks for the input. I shall work on this. I would like your input on how to have a backward compatibility on this.

**Comment by dylan-k** [comment]
Happy to help. Maybe I can test out any updates when they're ready.

**Comment by coyang** [comment]
> Fantastic extension. I could see using this a whole lot. I especially like it for the way it's also accessible as markdown files, but about that... the accessibility and utility could be improved. Outside of the extension, a filename like `_kei1dfird_1.md` simply doesn't do, because it's meaningless, I can't search for it by name, or even pick it from a files list.
> 
> Instead, perhaps, could it auto-rename according to the name of the item on the board, or allow for the markdown file to be changed? I guess it'll have to update the index too, and if you make the edit outside the extension you'll have to do that as well, but it's worth it for the longevity and accessibility of the files involved.
> 
> Anyway, thanks for listening and keep up the great work.

Thanks @vip20 's great work, this agile plugin is very useful to me.

I have the same requirement as @dylan-k 's proposual.

Hope @vip20  can implement this feature soon.

**Comment by vip20** [comment]
@coyang, thank you. I'll surely try. Currently I don't have a bandwidth for this. Once this is done, I shall update you here.
