### ISSUE TITLE
DOES NOT ALLOW SETTING PRIORITY & DEADLINE

### ISSUE THREAD

**Issue by knana1662** [vip20/vscode-agile-board#11]
Please help me out as I cannot set priorities and also deadlines as anytime i try to set a deadline and priority by clicking on the menu it automatically hides and also opens another blank vsagile page. Thank You 

NB:
I have tried it on another different device but same issues

**Comment by vip20** [comment]
Hi @knana1662, thank you for reporting the issue. I am held up in other tasks. I shall plan for this and take it up

**Comment by knana1662** [comment]
![Recorder N530 2023-03-28 0_52GMT](https://user-images.githubusercontent.com/109052744/228499707-58811474-814d-4fbe-af71-3931ed4c7efd.gif)

Ok this is how it works then with the image above. 
1. when I try to set deadline or priority, it doesn't work so I use Ctrl + Left Click or Alt + Click which opens some website like the one below:

https://[file+.vscode-resource.vscode-cdn.net](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/JHUICY/.vscode/extensions/vip20.vscode-agile-board-1.2.7/build/#)/c%3A/Users/USER/.vscode/extensions/vip20.vscode-agile-board-1.2.7/build/#

**Comment by vip20** [comment]
That seems like a file path in your local machine. Vs code manages the file path by itself. VS code update would've caused this issue. This app was built long time back. I'll have to update the version to match this.

**Comment by vip20** [comment]
The packages are outdated at this time. And VS Code dependencies got deprecated. I'll have to re-write the whole extension. If the extension is mostly needed, I can spend time re-writing this.

**Comment by knana1662** [comment]
Ok thanks i will be needing this anyway, please help me out, so far this seems to be the best extension i have downloaded and also will it take too much time (as in how many days) to rewrite it and also can you notify me when done so that i can use it without facing any problems. Thank You

**Comment by vip20** [comment]
I have cleaned the package. Activity bar icon is missing. I'll fix that on a later date.

[Release](https://marketplace.visualstudio.com/items?itemName=vip20.vscode-agile-board).

Feel free to create new issue if found any.
